---
title: "Interactive list of Biodiversity data sources"
description: 
site: distill::distill_website
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
# Load Libraries ----------------------------------------------------------
library(officer)
library(janitor)
library(ggtext)
library(tidyverse)
library(here)
library(DT)

```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
# Get the document --------------------------------------------------------
file<-list.files(paste0(here(),"/data"))

doc <- read_docx(paste0(here(),"/data/", file))


```


```{r,echo=FALSE, message=FALSE, warning=FALSE}
# Tidy the document -------------------------------------------------------

doc_tbl <- docx_summary(doc) %>% as_tibble()
#doc_tbl

# get the table cells
table_tbl <- doc_tbl %>%
  filter(content_type == "table cell")

#table_tbl

```


```{r,echo=FALSE, message=FALSE, warning=FALSE}
## Wrangle the table ##

## Table Headers ## 

table_header <- table_tbl %>%
  filter(is_header) %>%
  pull(text)

```


```{r,echo=FALSE, message=FALSE, warning=FALSE}
## Table Contents ##
BioD_tbl <- table_tbl %>%
  filter(!is_header) %>%
  select(text, row_id, cell_id) %>%
  pivot_wider(names_from = cell_id, values_from = text) %>%
  select(-row_id) %>% 
  set_names(table_header) %>%
  clean_names() 


```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
#Those data sources where at least some data (or mapping of data) appear to be instantly, freely and openly available are flagged with a star (*)

## Add column to indicate those that are instantly freely available
BioD_tbl<-BioD_tbl %>% 
  mutate("data_immediately_available"=ifelse(str_detect(data_source,"\\*")==TRUE, "Yes","No"))

```


```{r,echo=FALSE, message=FALSE, warning=FALSE}
tbl=BioD_tbl %>% 
  mutate(lead_agency= paste0('<a href="',url,'">',lead_agency,"</a>"))


```

```{r, echo=FALSE}
DT::datatable(tbl, 
              escape = FALSE)
```









